import type { Metadata } from "next";
import { Inter, Days_One } from "next/font/google";
import "./globals.css";

const inter = Inter({
    subsets: ["latin", "cyrillic"],
    variable: "--font-inter",
});

const days_one = Days_One({
    weight: "400",
    subsets: ["latin"],
    variable: "--font-days-one",
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" className={`${inter.variable} ${days_one.variable}`}>
            <body
                className="font-inter antialiased"
            >
                {children}
            </body>
        </html>
    );
}
